### ISSUE TITLE
Milestone 1 Report - Coding Work Summary

### ISSUE THREAD

**Issue by cakmadam98** [bounswe/bounswe2020group7#182]
A summary of coding work done by each team member. 
Deadline is 29.11.2020 10:00.

- [ ] Umutcan Uvut

- [x] Hilal Demir

- [x] Ahmet Dadak

- [x] Burhan Akkuş

- [ ] Orkan Akisu

- [x] Alperen Divriklioğlu

- [x] Burak Ömür

- [ ] Hasan Ramazan Yurt

- [x] Ertuğrul Bülbül

- [x] Öykü Yılmaz

- [x] Hüseyin Can Bölükbaş

- [x] Halil Umut Özdemir

**Comment by cakmadam98** [comment]
As a backend team member;
- Implemented FollowRequestsAPI(GET, POST, DELETE)
- Implemented FollowersAPI(GET)
- Implemented FollowingsAPI(GET)
- Reviewed merge requests of the backend team.

**Comment by hilal-demir** [comment]
As a backend team member;

Implemented JobsAPI(GET, POST, PUT, DELETE)
Implemented SkillsAPI(GET, POST, PUT, DELETE)
Implemented Unit Tests for my APIs
Kept track of the issues and code reviews from Github

**Comment by BurhanAkkus** [comment]
As a frontend team member;

Implemented HomePage InfiniteScroll
Implemented HomePageNotifications
Implemented General Layout of Website
Reviewed merge requests of the frontend team.

**Comment by oykuyilmaz1** [comment]
Implemented ProfilePage
Implemented Followers-Following Page
Implemented Edit profile page

**Comment by ahmetdadak** [comment]
Implemented
- Authentication mechanism for webpage
- Landing page for guest user
- Login page
- Register page
- Forgot password page
- Reset password page
- Account verification page
- Follow mechanism in profile page
- Backend connection of edit profile page

**Comment by darktheorys** [comment]
# ANDROID
___
* Implemented home page for guests
* Implemented login page
* Implemented register page
* Implemented reset password page
* Implemented Retrofit2 and RX kotlin for requests.

**Comment by ertbulbul** [comment]
Researched about MVP architecture.
Implemented initial project using MVP architecture.
Design of the pages are done with the Android team.
Researched about Retrofit and its practices.
Implemented the REST API interface using Retrofit.
Implemented home page.
Implemented an interface to provide connection between the repository and presenter class.

**Comment by HUmutOzdemir** [comment]
* Initial Database Design was Done with the Backend Team
* Made Research about Flask and Create Initial Project Structure
* Created a Base Unit Test Class which Provides a Capability of Unit Tests which uses Database
* Implemented Login Mechanism (POST)
* Implemented Reset Password Mechanism (GET,POST)
* Implemented E-Mail Mechanism of Backend Server 
* Implemented Notification Mechansim (GET,DELETE)
* Implemented a Mechanism that Fetches Reserach Information from Google Scholar(API) and ResearchGate(HTML Parsing)
* Implemented a Background Process that will Update GS and RG information of all users in the system
* Implemented Ednpoints of Research Information (GET,POST,PUT,DELETE)
* Implemented Unit Tests for Each Funtionality that I implemeted
* Created a CI/CD Pipeline using Travis-CI (Prepared some scripts to make deploment easy)
* Creaed Dockerfiles of the project with Alperen Divriklioğlu and Ahmet Dadak

**Comment by alperendivriklioglu** [comment]
As a member of the backend team, I

- created the Dockerfile for the backend app,
- created the Docker Composefile for the backend and the database services combined, which later served as the base of the Composefile for the whole project (frontend - backend - database)
- implemented a RESTful API for the "User" resource (namely, the endpoints for creating, reading, updating and deleting a user)
- implemented the endpoint for the user activity stream filler. (we had not implemented the "activity stream" yet but needed an endpoint to return static content for the milestone presentation)

**Comment by cakmadam98** [comment]
Milestone 1 is completed.
